### ISSUE TITLE
Macro examples needed

### ISSUE THREAD

**Issue by weber8722** [varianus/ovotext#1]
Hi, I see someone is working on a macro recorder, which is great! However, often I do not need a full macro recorder, because I already KNOW what I want to execute automatically, like I want to replace one string with another. This is the most-required action I need to do on existing documents. Having some examples on how to do that (=pure macro execution) would be great. And it could be released before we have the full macro recording/execute functionality.

In DOS times I made something similar, with Wordstar syntax (Ctrl-Y, Ctrl-K-B, Ctrl-F, Ctrl-K-K, etc.). But this editor would only run in a DOS box (if at all).

**Comment by varianus** [comment]
If I understand correctly, you want to directly edit a macro source code to automate text substitution.

I was already thinking about this feature, manipulation of log files is one of the reasons why I extended the macro recorder with text replacement and other actions (uppercase / lowercase, space deletion, etc.).

The language used for the macro source code is simple and readable, but I can't find any documentation on the web.
For example, this macro will replace the XML tag foo with bar 
```
macro unnamed
begin
  ecReplace <foo>       <bar>  [ssoEntireScope,ssoReplaceAll]
  ecReplace </foo>      </bar> [ssoEntireScope,ssoReplaceAll]
end  
```
